spring:
  jpa:
    database: mysql
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

  datasource:
    url: ENC(4fvl7ILQT3u3FmMRDAWlliQC7Y09dKterHs7oeoMQk5NB4efhfGCjQGJUoNHHpgc7X5xc+Fhr4cra7EPjbteEfNk9aT7RXdtQQh260sUAccuNift8poidg==)
    hikari:
      username: ENC(KBBydhmLF2zSJKdRwl3v5w==)
      password: ENC(7IGfZuXmZBhWJZ5Sw37Ikg==)
