server:
  port: 3000

spring:
  application:
    name: batch-app
  ### Jpa Config
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
    database-platform: org.hibernate.dialect.MySQL57Dialect


### Logger Config
logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE


