spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: always
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

server:
  port: 3000
